blueprint:
  name: Motion-activated Light with lux
  description: Turn on a light when motion is detected is lux is bellow n.
  domain: automation
  source_url: https://raw.githubusercontent.com/pingformat/HA/refs/heads/main/test.yaml
  author: Pingformat
  input:
    motion_entity:
      name: Motion Sensor Lux
      selector:
        entity:
          filter:
            - device_class: occupancy
              domain: binary_sensor
            - device_class: motion
              domain: binary_sensor
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    lux_entity:
      name: Lux Sensor
      selector:
        entity:

    lux_level_bellow:
      name: Max Lux
      description: Max lux, above that the light will not turn on
      default: 5
      selector:
        number:
          min: 0
          max: 5000
          unit_of_measurement: lx

mode: restart
max_exceeded: silent

triggers:
  trigger: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

actions:
  - alias: "Turn on the light"
    action: light.turn_on
    target: !input light_target
  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      trigger: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - alias: "Wait the number of seconds that has been set"
    delay: !input no_motion_wait
  - alias: "Turn off the light"
    action: light.turn_off
    target: !input light_target
